name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup rust environment
      run: rustup target add wasm32-unknown-unknown
    - name: Build WASM
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Build Native (Linux)
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Run clippy
      run: cargo clippy --verbose
